from datetime import datetime
from marshmallow import *
from service import db

class Booking(db.Model):
    __tablename__           = 'tr_booking'
    BOOKING_ID              = db.Column(db.String(), primary_key = True)
    EMAIL                   = db.Column(db.String(), primary_key = True)
    WS_ID                   = db.Column(db.String())
    WS_IN_TRAINING          = db.Column(db.String())
    WS_NAME                 = db.Column(db.String())
    WS_ADDRESS              = db.Column(db.String())
    PIT_ID                  = db.Column(db.String())
    WSP_ID                  = db.Column(db.String())
    WSP_DATE                = db.Column(db.String())
    WSP_DESC                = db.Column(db.String())
    WS_EMPLOYEE_NAME        = db.Column(db.String())
    WS_EMPLOYEE_ID          = db.Column(db.String())
    KTP                     = db.Column(db.String())
    NAME                    = db.Column(db.String())
    USER_LATITUDE           = db.Column(db.String())
    USER_LONGITUDE          = db.Column(db.String())
    ADDRESS                 = db.Column(db.String())
    ON_SITE_LATITUDE        = db.Column(db.String())
    ON_SITE_LONGITUDE       = db.Column(db.String())
    ON_SITE_ADDRESS         = db.Column(db.String())
    ON_SITE_ADDRESS_REMARKS = db.Column(db.String())
    DOB                     = db.Column(db.String())
    PHONE                   = db.Column(db.String())
    UV_ID                   = db.Column(db.String())
    UV_NAME                 = db.Column(db.String())
    UV_LICENSE_PLATE        = db.Column(db.String())
    UV_ASSEMBLE_YEAR        = db.Column(db.String())
    VIN                     = db.Column(db.String())
    VS_ID                   = db.Column(db.String())
    VS_DESC                 = db.Column(db.String())
    CC_ID                   = db.Column(db.String())
    CC_DESC                 = db.Column(db.String())
    VF_ID                   = db.Column(db.String())
    VF_DESC                 = db.Column(db.String())
    VTRANS_ID               = db.Column(db.String())
    VTRANS_DESC             = db.Column(db.String())
    VT_ID                   = db.Column(db.String())
    VT_DESC                 = db.Column(db.String())
    VB_ID                   = db.Column(db.String())
    VB_DESC                 = db.Column(db.String())
    VRS_ID                  = db.Column(db.String())
    VRS_DESC                = db.Column(db.String())
    VM_ID                   = db.Column(db.String())
    VM_DESC                 = db.Column(db.String())
    VC_ID                   = db.Column(db.String())
    VC_DESC                 = db.Column(db.String())
    UV_ENGINE_NO            = db.Column(db.String())
    NUMBER_OF_UPDATE        = db.Column(db.String())
    KM                      = db.Column(db.String())
    OTHER_SERVICE           = db.Column(db.String())
    REMARKS                 = db.Column(db.String())
    REMARKS_BY_SA           = db.Column(db.String())
    STATUS                  = db.Column(db.String())
    VERIFICATION_CODE       = db.Column(db.String())
    HAS_REASON              = db.Column(db.String())
    BONUS_ID                = db.Column(db.String())
    SCANNABLE               = db.Column(db.String())
    DURATION                = db.Column(db.String())
    START_SLOT              = db.Column(db.String())
    START_SLOT_LABEL        = db.Column(db.String())
    END_SLOT                = db.Column(db.String())
    END_SLOT_LABEL          = db.Column(db.String())
    START_TIME              = db.Column(db.String())
    CHECKED_IN_BY           = db.Column(db.String())
    END_TIME                = db.Column(db.String())
    CHECKED_OUT_BY          = db.Column(db.String())
    NOTIFICATION_STATUS     = db.Column(db.String())
    BOOKING_TYPE            = db.Column(db.String())
    VALIDATION              = db.Column(db.String())
    IS_FINAL_STATUS         = db.Column(db.String())
    CONFIRMATION_ISSUED     = db.Column(db.String())
    CONFIRMATION_REASON     = db.Column(db.String())
    INVALID_REASON          = db.Column(db.String())
    RECONFIRMATION_REASON   = db.Column(db.String())
    VALID_REASON            = db.Column(db.String())
    APPLICATION_ID          = db.Column(db.String())
    TAKSASI_CODE            = db.Column(db.String())
    ENABLE_UPLOAD_EVIDENCE  = db.Column(db.String())
    REIMBURSE_STATUS        = db.Column(db.String())
    REIMBURSE_REMARK        = db.Column(db.String())
    BATCH_SCAN              = db.Column(db.String())
    CREATED_AT              = db.Column(db.DateTime, default=datetime.now())
    CREATED_BY              = db.Column(db.String())
    UPDATED_AT              = db.Column(db.DateTime, onupdate=datetime.now)
    UPDATED_BY              = db.Column(db.String())
    DELETE_AT               = db.Column(db.DateTime)
    DELETE_BY               = db.Column(db.String())